# Tarea de algebra linea con python
# Rachit Vargas

###### Ejercicio 1

In [1]:
import numpy as np

a = np.array([2,-5,4,6,-3])
b = np.array([5,-2,1,-7,-4])

u = 4 * a
v = 3 * b
resultado = u - v
print(resultado)

[ -7 -14  13  45   0]


##### Ejercicio 2

In [2]:
import numpy as np

a = np.array([2,-5,4,6,-3])
b = np.array([5,-2,1,-7,-4])

u =  5 * a
v = 3 * b

resultado = u + v
print(resultado)

[ 25 -31  23   9 -27]


##### Ejercicio 3

In [3]:
import numpy as np

a = np.array([2,-5,4,6,-3])
b = np.array([5,-2,1,-7,-4])

resultado = np.dot(a,b)
print(resultado)

-6


##### Ejercicio 4

In [1]:
import numpy as np

a = np.array([2,-5,4,6,-3])
b = np.array([5,-2,1,-7,-4])

norma_u = np.linalg.norm(a)
norma_v = np.linalg.norm(b)

print(norma_u)
print(norma_v)

9.486832980505138
9.746794344808963


##### Ejercicio 5

In [1]:
import numpy as np

a = np.array([2,-5,4,6,-3])
b = np.array([5,-2,1,-7,-4])


def mul(a, b):
    return np.dot(a,b)

def norma_2(b):
    return np.linalg.norm(b) ** 2

def resul (calcular_mul, calcular_norma_2):
    return calcular_mul / calcular_norma_2

calcular_mul = mul(a,b)
calcular_norma_2 = norma_2(b)
resultado = resul(calcular_mul, calcular_norma_2)

proj = resultado * b
print(proj)

[-0.31578947  0.12631579 -0.06315789  0.44210526  0.25263158]


##### Ejercicio 6

In [3]:
import numpy as np

a = np.array([2,-5,4,6,-3])
b = np.array([5,-2,1,-7,-4])


def dist(a,b):
    return np.linalg.norm(a - b)

distancia = dist(a,b)
print(distancia)

14.035668847618199


## Determinar el vector v identificado con el segmento de linea dirigido PQ para los puntos P(1,−8,−4,6) y Q(3, −5, 2, −4)


In [5]:
import numpy as np

p = np.array([1, -8, -4, 6])
q = np.array([3, -5, 2, -4])

v = q - p
print(v)

[  2   3   6 -10]


## Determinar un vector unitario w ortogonal a u = [1, 2, 3] y v = [1, −1, 2]


In [9]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([1, -1, 2])


def calcul_cross(u,v):
    return np.cross(u, v)

def norma_cruz(cruz):
    return np.linalg.norm(cruz)

cruz = calcul_cross(u,v)
norma = norma_cruz(cruz)
w = cruz / norma

print(w)

[ 0.91132238  0.13018891 -0.39056673]


## Calcular ( u x v ) dados u = 3i − 4j + 2k y v= 21i + 5j − 3k

In [8]:
import numpy as np


u = np.array([3, -4, 2])
v = np.array([21, 5, -3])

resultado = np.cross(u,v)
print(resultado)

[ 2 51 99]


## Sea u = (1 + 7i , 2 − 6i) y v = (5 − 2i , 3 − 4i) determine:

##### u + v

In [4]:
import numpy as np


u = np.array([1 + 7j, 2 - 6j])
v = np.array([5 -2j, 3 - 4j])

resultado = u + v

print(resultado)

[6. +5.j 5.-10.j]


##### (3 + 1j) * u

In [1]:
import numpy as np

a = np.array([3 + 1j])
u = np.array([1 + 7j, 2 -6j])
resultado = a * u

print(resultado)

[-4.+22.j 12.-16.j]


###### u * v

In [5]:
import numpy as np


u = np.array([1 + 7j, 2 - 6j])
v = np.array([5 -2j, 3 - 4j])

resultado = u * v

print(resultado)

[ 19.+33.j -18.-26.j]


##### || u || y || v ||

In [7]:
import numpy as np


u = np.array([1 + 7j, 2 - 6j])
v = np.array([5 -2j, 3 - 4j])

resultado_1 = np.linalg.norm(u)
resultado_2 = np.linalg.norm(v)

print(resultado_1)
print(resultado_2)

9.486832980505138
7.3484692283495345


## Ejercicio de matrices

##### B * A y B * A

In [1]:
import numpy as np

a = np.array([[9,1,-3], [6, -5, 4], [7, 2, 8]])
b = np.array([[12, -7, -7], [0, -2, 4]])

result_1 = 0

try:    
    result_1 = np.dot(a, b)
    print(result_1)

except:
    
    print("Ha ocurrido un error en esta operacion")
    
result_2 = 0

try:    
    result_2 = np.dot(b, a)
    print(result_2)
except:
    print("Ha ocurrido un error en esta operacion")
    

Ha ocurrido un error en esta operacion
[[  17   33 -120]
 [  16   18   24]]


#### I * A y 0 * A

In [2]:
import numpy as np

identidad = np.identity(3)
a = np.array([[9,1,-3], [6, -5, 4], [7, 2, 8]])

resultado = np.dot(identidad, a)

escalar = 0

resultado_2 = np.dot(escalar, a)

print(resultado)
print(resultado_2)

[[ 9.  1. -3.]
 [ 6. -5.  4.]
 [ 7.  2.  8.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


###### A^T y A + A^T

In [3]:
import numpy as np

a = np.array([[9,1,-3], [6, -5, 4], [7, 2, 8]])
a_traspuesta = a.T
print(a_traspuesta)
    

result = a + a_traspuesta
print(result)


[[ 9  6  7]
 [ 1 -5  2]
 [-3  4  8]]
[[ 18   7   4]
 [  7 -10   6]
 [  4   6  16]]


##### C = BB^T

In [6]:
import numpy as np

b = np.array([[12, -7, -7], [0, -2, 4]])
b_traspuesta = b.T

c = np.dot(b, b_traspuesta)
print(c)
print(c.T)

if (c == c.T).any():
    print('Esta matriz es simetrica')
else:
    print('Esta matriz no  es simetricas')

[[242 -14]
 [-14  20]]
[[242 -14]
 [-14  20]]
Esta matriz es simetrica


##### Dertminante de C

In [7]:
import numpy as np

b = np.array([[12, -7, -7], [0, -2, 4]])
b_traspuesta = b.T

c = np.dot(b, b_traspuesta)

determinante_c = np.linalg.det(c)
print(determinante_c)

4643.999999999999


##### Matriz inverso de C

In [8]:
import numpy as np

b = np.array([[12, -7, -7], [0, -2, 4]])
b_traspuesta = b.T

c = np.dot(b, b_traspuesta)

c_inverso = np.linalg.inv(c)
print(c_inverso)

[[0.00430663 0.00301464]
 [0.00301464 0.05211025]]
